# Site settings
title:       terminal.tips
email:       inbox@trevorbramble.com
author:      Trevor Bramble
description: "Master your terminal, one tip at a time"
baseurl:     ""
url:         "http://terminal.tips"

# Google analytics
google_analytics: UA-39279846-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_navigation:    true
show_post_minutes:  false

# Social icons
show_social_icons: false
github_username: TrevorBramble
twitter_username: TrevorBramble
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
exclude: ["Gemfile", "Gemfile.lock", "CNAME"]
